### ISSUE TITLE
Module d'export : limit&offset

### ISSUE THREAD

**Issue by MathildeLeclerc** [PnX-SI/gn_module_export#101]
Nous avons constaté un problème au niveau de l'API du module d'export en utilisant GN2PG. 

La requête SQL avec limit et offset renvoie des données aléatoirement du fait qu'il n' y ait pas d'order by pour ordonner les données.

D'après la documentation de postgresql : https://www.postgresql.org/docs/9.3/queries-limit.html
"When using LIMIT, it is important to use an ORDER BY clause that constrains the result rows into a unique order. Otherwise you will get an unpredictable subset of the query's rows."

Par conséquent, certaines données sont manquantes et d'autres sont répétées.

**Comment by amandine-sahl** [comment]
Effectivement ceci dit pour ordonner correctement il faudrait une colonne de type unique ce qui actuellement n'est pas le cas

**Comment by camillemonchicourt** [comment]
Comme on ne connait pas à l'avance les colonnes dans chaque export vu qu'ils sont basés sur des vues que chacun construit comme il veut, il faut rajouter un champs dans la table des exports pour que l'utilisateur puisse indiquer un ou plusieurs champs à utiliser pour le order_by

**Comment by camillemonchicourt** [comment]
Possibilité ajoutée dans les filtres de l'API et indiqués dans le Swagger (https://github.com/PnX-SI/gn_module_export/pull/107/files)

**Comment by camillemonchicourt** [comment]
Fait dans la version 1.3.0 du module, avec l'ajout du paramètre ``orderby=nom_col[ASC|DESC]`` au niveau de l'API des exports
