### ISSUE TITLE
Proxy Error - requête longue

### ISSUE THREAD

**Issue by Idaline** [PnX-SI/gn_module_export#104]
Bonjour,

Il m'est impossible de créer un export, sûrement car la requête est assez longue (~2min). Y-a-t-il un moyen de régler ce problème svp ? 

Après avoir créer mon export et cliquer sur 'Save', je reçois : 

Proxy Error

The proxy server received an invalid response from an upstream server.
The proxy server could not handle the request

Reason: Error reading from remote server

Apache/2.4.38 (Debian) Server at geonature.creamontblanc.org Port 443

**Comment by amandine-sahl** [comment]
Le problème vient du fait que le fichier est servi par gunicorn et non apache. Il faut changer la configuration d'apache comme indiqué dans les README : https://github.com/PnX-SI/gn_module_export/blob/master/README.md#url-des-fichiers
cf :  https://github.com/PnX-SI/gn_module_export/issues/73

**Comment by Idaline** [comment]
Ok, merci !
