### ISSUE TITLE
[1.2.5] Affichage des exports: conflit id_organisme et id_role

### ISSUE THREAD

**Issue by maximetoma** [PnX-SI/gn_module_export#108]
Bonjour, 

J'ai un petit soucis de permissions/affichage sur le module Exports.

En fait, pour un groupe d'utilisateurs, tous les exports s'affichent pour les utilisateurs de ce groupe alors que ça ne devrait pas.
Je n'arrive malheureusement pas à déterminer d'où vient le problème...
J'ai essayé de reprendre un groupe à zéro et en remettant un des membres de l'ancien groupe en question (et en le supprimant de l'ancien groupe) avec cette configuration de perms : 

<html xmlns:v="urn:schemas-microsoft-com:vml"
xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:x="urn:schemas-microsoft-com:office:excel"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=Excel.Sheet>
<meta name=Generator content="Microsoft Excel 15">
<link id=Main-File rel=Main-File
href="file:///C:\Users\MAXIME~1.TOM\AppData\Local\Temp\msohtmlclip1\01\clip.htm">
<link rel=File-List
href="file:///C:\Users\MAXIME~1.TOM\AppData\Local\Temp\msohtmlclip1\01\clip_filelist.xml">

</head>

<body link="#0563C1" vlink="#954F72">

nom_role | module_code | code_object | code_action | label_filter | code_filter_type
-- | -- | -- | -- | -- | --
Groupe_RNBA_p | GEONATURE | ALL | C | Les données de mon organisme | SCOPE
Groupe_RNBA_p | GEONATURE | ALL | R | Les données de mon organisme | SCOPE
Groupe_RNBA_p | GEONATURE | ALL | U | Les données de mon organisme | SCOPE
Groupe_RNBA_p | GEONATURE | ALL | V | Les données de mon organisme | SCOPE
Groupe_RNBA_p | GEONATURE | ALL | E | Les données de mon organisme | SCOPE
Groupe_RNBA_p | GEONATURE | ALL | D | Les données de mon organisme | SCOPE
Groupe_RNBA_p | ADMIN | ALL | C | Aucune donnée | SCOPE
Groupe_RNBA_p | ADMIN | ALL | R | Aucune donnée | SCOPE
Groupe_RNBA_p | ADMIN | ALL | U | Aucune donnée | SCOPE
Groupe_RNBA_p | ADMIN | ALL | V | Aucune donnée | SCOPE
Groupe_RNBA_p | ADMIN | ALL | E | Aucune donnée | SCOPE
Groupe_RNBA_p | ADMIN | ALL | D | Aucune donnée | SCOPE
Groupe_RNBA_p | EXPORTS | ALL | C | Mes données | SCOPE
Groupe_RNBA_p | EXPORTS | ALL | R | Mes données | SCOPE
Groupe_RNBA_p | EXPORTS | ALL | U | Mes données | SCOPE
Groupe_RNBA_p | EXPORTS | ALL | V | Mes données | SCOPE
Groupe_RNBA_p | EXPORTS | ALL | E | Mes données | SCOPE
Groupe_RNBA_p | EXPORTS | ALL | D | Mes données | SCOPE

</body>

</html>

Mais toujours le même soucis...
Avez-vous une idée ? Un bug potentiel ?

Merci

**Comment by camillemonchicourt** [comment]
Je ne suis pas certain du fonctionnement du CRUVED dans le module EXPORT.
D'autant plus qu'il y a une gestion des droits d'accès aux exports un peu différent dans ce module : https://github.com/PnX-SI/gn_module_export#associer-les-roles-ayant-la-permission-dacc%C3%A9der-%C3%A0-cet-export

Soit on indique qu'un EXPORT est public et tout le monde le voit, soit on liste les rôles qui ont accès à l'export.

Je sais pas si le CRUVED fonctionne aussi et complète ce fonctionnement ?

**Comment by maximetoma** [comment]
Oui effectivement, j'ai oublié de préciser:
- Mes exports sont tous en "NON-PUBLIC"
- J'attribus généralement un export à 2 rôles : le rôle admin + le rôle de la réserve en question

Mais dans mon cas, quand j'ai recréé un nouveau groupe, je n'ai pas associé d'export à ce nouveau groupe. Ainsi normalement il devrait s'afficher aucun export. Mais ce n'est pas le cas... :)

**Comment by camillemonchicourt** [comment]
OK il y a peut-être un soucis au niveau du module.
A voir si @amandine-sahl peut apporter des précisions.

**Comment by maximetoma** [comment]
Après moultes prospections j'ai enfin trouvé où était le problème !

En fait, il vient d'un conflit entre l'id_organisme et l'id_role.
Mon groupe ADMIN porte l'id 9 et l'id_organisme de la "Baie de l'Aiguillon" porte également le numéro 9.

En changeant, la valeur d'id organisme, les exports reliés au role "Groupe ADMIN" n'apparaissent donc plus aux yeux des membre de l'organisme "Baie de l'Aiguillon"

Je ne sais pas en revanche où se situe le problème dans le code...

**Comment by camillemonchicourt** [comment]
OK alors ça doit être un soucis au niveau global des permissions et du CRUVED de GeoNature

**Comment by bouttier** [comment]
Le problème ce situe ici : https://github.com/PnX-SI/gn_module_export/blob/master/backend/repositories.py#L256
Je ne sais pas s’il y avait pour but à un moment de pouvoir donner accès à un export à un organisme donnée, mais je n’en retrouve pas la trace, et ce n’est pas possible de faire comme cela : CorExportsRoles contient une FK vers un rôle et non un organisme … (et il n’est pas possible de différentier un id role d’un id organisme de la sorte).

**Comment by camillemonchicourt** [comment]
En effet il était seulement prévu de donner des droits sur un export à une personne ou un groupe de personnes, pas un organisme.

**Comment by camillemonchicourt** [comment]
Corrigé dans la 1.2.7
