### ISSUE TITLE
Ajouter export WFS

### ISSUE THREAD

**Issue by camillemonchicourt** [PnX-SI/gn_module_export#11]
Il a été proposé d'ajouter un export WFS. 
Il est déjà prévu un export CSV, GeoJSON et SHP. Il est aussi prévu que chaque Export puisse être accessible sous forme d'API. 
Le WFS pose des questions de performance mais aussi d'architecture car il nécessite d'ajouter un serveur carto au projet (MapServer, Geoserver ou QGIS server). 
Du coup, on propose de ne pas l'intégrer nativement mais que chacun puisse faire des exports WFS si il le souhaite en branchant un serveur carto à sa BDD GeoNature.

**Comment by orovellotti** [comment]
C'est effectivement très lourd de rajouter un serveur Carto … 

Ou en est on au niveau des obligations "Inspire", il faut aussi publibier les meta données ?

**Comment by camillemonchicourt** [comment]
Oui ce n'est pas souhaité d'ajouter un serveur carto dans GeoNature. 

Pour Inspire, bof... Mais on gère les métadonnées SINP dans GeoNature : https://github.com/PnX-SI/GeoNature/issues/268

Du coup, on avait évoqué l'idée d'intégrer des infos sur les métadonnées d'un jeu de données dans l'export des données de celui-ci.

**Comment by camillemonchicourt** [comment]
On n'intégrera pas de flux WMS/WFS nativement dans GeoNature. 
Libre à chacun d'en mettre en place en se connectant directement à la BDD de GeoNature.

Par contre l'idée de joindre les métadonnées lors d'un export est une piste intéressante d'évolution.
