### ISSUE TITLE
Modifier l'identifiant CA pour les données d'ABC

### ISSUE THREAD

**Issue by AmelieTagliaferro** [PnX-SI/gn_module_export#115]
Bonjour, 
je ne sais pas si cet issue se trouve au bon endroit, mais j'ai une question qui concerne les métadonnées et l'export. 
En effet, en rebouclant avec l'OFB sur la gestion des données d'un ABC, il s'avère que l'OFB peut créer des métafiches lors de la validation d'un projet d'ABC, créant ainsi automatiquement un identifiant pour le CA SINP du projet. 
Les données collectées dans le cade de cet ABC sont envoyées à la DREAL pour transfère au SINP avant de retrouver les données de l'ABC sur le site https://abc.naturefrance.fr/ grâce à l'identifiant du CA. 
Cependant, sur geonature lors de la création du CA des données de l'ABC, un identifiant SINP est automatiquement créé. 
Est il possible de le modifier manuellement pour le faire correspondre avec celui créé par l'OFB ? 
Merci d'avance pour vos retours, 
Bonne fin de journée, 
Amélie

**Comment by DonovanMaillard** [comment]
Bonjour, 

Ce n'est effectivement pas lié au module export. C'est lié au coeur de GeoNature, pour modifier cet uuid il faut aller modifier la valeur dans la base de données (administrateur) dans le schéma des métadonnées (gn_meta.t_acquisition_frameworks).
