### ISSUE TITLE
Configuration du module non accéssible (installation en cours)

### ISSUE THREAD

**Issue by DonovanMaillard** [PnX-SI/gn_module_export#116]
Bonjour, 

Sur une instance Geonature en 2.9.2, exports à jour sur la dernière version, sur un serveur en Debian11.

A chaque update de configuration, je retrouve le message suivant : ``Configuration du module non accéssible (installation en cours).``

Tout semble bien fonctionner, mon fichier ``conf_gn_module.toml`` est bien présent dans mon répertoire ``gn_module_export/config/``. J'avais dans un premier temps défini que l'url des exports, puis j'ai testé à l'instant de reprendre tout ce qui est dans le ``.example`` en ajustant les variables, ça ne change rien. 

Le message d'erreur avec cette coquille (accent sur "accéssible") n'est pas présente dans les autres modules disponibles sur mon instance, je suppose donc que c'est du coté de l'export que j'ai mon erreur. 

Est-ce que d'autres ont également ce soucis? Ou est-ce que quelqu'un voit d'où ça pourrait venir ? Je vais repasser toutes les notes de versions des updates pour voir si j'ai pas raté quelque chose...

**Comment by camillemonchicourt** [comment]
J'ai le même soucis depuis hier soir, mais sur Monitoring : 

```
(venv) geonatadmin@geonature2:~/geonature$ geonature update_module_configuration monitorings --build=false
Configuration du module non accéssible (installation en cours)
Pensez à relancer geonature (sudo systemctl restart geonature)
Pensez à relancer geonature (sudo systemctl restart geonature)
```

Cela a cassé le build général de notre GeoNature.

Peux-tu indiquer précisément les commandes que tu as lancé ?

**Comment by TheoLechemia** [comment]
Oui c'est l'export qui lance ce warning. Pas problématique, car n'empêche pas les commandes d'aller au bout, mais il faudrait voir pourquoi il s'affiche tout le temps

**Comment by amandine-sahl** [comment]
C'est à cause de l'exposition de l'api dsw : https://github.com/PnX-SI/gn_module_export/blob/f392a128854ce2e65767730f204cff6831e0b0d3/backend/blueprint.py#L575

**Comment by DonovanMaillard** [comment]
aucun soucis de mon coté en revanche au niveau du build, uniquement cette alerte mais tout le reste fonctionne sans soucis.

**Comment by camillemonchicourt** [comment]
Pour mon build cassé, c'était un autre soucis au niveau de Monitoring.

**Comment by camillemonchicourt** [comment]
A priori plus le cas dans les versions récentes du module.
