### ISSUE TITLE
Interface Admin : Ajout de champ token dans la table gn_exports.cor_exports_roles et merge de la vue "associer un rôle à un export" dans la vue "Export"

### ISSUE THREAD

**Issue by andriacap** [PnX-SI/gn_module_export#131]

**Comment by camillemonchicourt** [comment]
Actuellement il faut passer un login / mot de passe pour accéder à l'API json d'un export.
Il est proposé de passer plutôt par un token, plus facile à partager et utiliser quand on interroge une API.
Pour cela, on ajoute un champs `token` dans la table `gn_exports.cor_exports_roles`.

**Comment by lpofredc** [comment]
Ok, ce n'est pas sans conséquences sur GN2PG. qui devra utiliser les 2 dispositifs d'authentification, le login pour récupérer l'url du module d'export, le token pour récupérer l'export ? A moins que l'on ne puisse utiliser les deux pour l'export (authentification clasdique OU token) ?

**Comment by camillemonchicourt** [comment]
Salut, on a pensé à GN2PG qui aurait tout intérêt à passer par un token, à terme.
Mais on a gardé la rétrocompatibilité avec l'authentification à l'API d'un export avec login/mdp.

On avait pas en tête que GN2PG utilisait aussi une autre route pour récupérer l'URL du module Export.
A priori, il nous semble que c'est dommage de devoir générer dynamiquement l'URL de l'API et qu'il vaudrait mieux passer à GN2PG directement l'URL complète de l'API de l'export sans chercher à la générer dynamiquement. 
Exemple : https://demo.geonature.fr/geonature/api/exports/api/1
