### ISSUE TITLE
Suppression de la table loggant les exports (t_exports_logs)

### ISSUE THREAD

**Issue by camillemonchicourt** [PnX-SI/gn_module_export#136]
Cette table permet de tracer tous les exports à la demande ainsi que les appels API d'un export.

L'usage de celle-ci (ainsi que de la vue associée `v_exports_logs`) est discutable et incertain.
Elle complique le code, donc il est proposé de la supprimer si non utilisée.

Contenu de la table : 

```
    CREATE TABLE gn_exports.t_exports_logs
    (
        id SERIAL NOT NULL PRIMARY KEY,
        id_role integer NOT NULL,
        id_export integer,
        format character varying(10) NOT NULL,
        start_time TIMESTAMP NOT NULL,
        end_time TIMESTAMP,
        status numeric DEFAULT '-2'::integer,
        log text,
        CONSTRAINT fk_export FOREIGN KEY (id_export)
            REFERENCES gn_exports.t_exports (id) MATCH SIMPLE
            ON UPDATE NO ACTION
            ON DELETE NO ACTION,
        CONSTRAINT fk_user FOREIGN KEY (id_role)
            REFERENCES utilisateurs.t_roles (id_role) MATCH SIMPLE
            ON UPDATE NO ACTION
            ON DELETE NO ACTION
    );
```

**Comment by gildeluermoz** [comment]
Je vois 2 usages différents des logs : soit ils sont purement informatifs soit on peut avoir besoin de leur contenu pour travailler sur les données en sql. 
Dans le premier cas des logs en mode fichier avec logrotate semblent plus adaptés, dans le second cas il est utile de les avoir en base.

**Comment by camillemonchicourt** [comment]
Ce ne sont pas des logs techniques pour identifier les soucis ou autres.
C'est une table listant et historisant les exports qui ont été réalisés (par qui et quand).
