### ISSUE TITLE
Liste des exports en fonction de gn_exports.cor_exports_roles

### ISSUE THREAD

**Issue by camillemonchicourt** [PnX-SI/gn_module_export#14]
Ne lister à l'utilisateur que les exports pour lesquels il a des droits (si son ``id_role`` ou celui d'un de ses groupes présent dans ``gn_exports.cor_exports_roles`` pour les exports à lui lister)

**Comment by camillemonchicourt** [comment]
Et dans le fichier ``sample.sql``, il faudrait voir comment peupler cette table pour attribuer les accès aux 2 groupes de bases présents dans ``utilisateurs.t_roles`` : Grp_admin et Grp_en_poste. 
Pourquoi pas en utilisant leurs noms vu qu'on ne maitrise pas leurs ``id_role`` : 

```SQL
INSERT INTO gn_exports.cor_exports_roles (id_export, id_role)
WITH exports AS (
  SELECT id FROM gn_exports.t_exports
  )
SELECT exports.id, r.id_role
FROM utilisateurs.t_roles r, exports
WHERE r.nom_role = 'Grp_en_poste' or r.nom_role = 'Grp_admin'
```

**Comment by camillemonchicourt** [comment]
En effet, ça semble totalement inutile car la vue ``utilisateurs.v_usersaction_forall_gn_modules```gère déjà ça bien mieux et retourne le CRUVED de chaque utilisateur, en fonction de son propre CRUVED ou de celui de ses groupes, sans avoir à retrouver ensuite dans quels groupes il se trouve...
Et il y a déjà les routes associées à cette vue.

**Comment by amandine-sahl** [comment]
cf #37
