### ISSUE TITLE
install_db.sh, settings et logs

### ISSUE THREAD

**Issue by camillemonchicourt** [PnX-SI/gn_module_export#18]
Pour utiliser le fichier settings.ini de GeoNature et loguer l'installation dans le répertoire du module, voir l'exemple de ce module : https://github.com/PnX-SI/gn_module_suivi_flore_territoire/blob/master/install_db.sh

En effet, on n'a plus de log globaux au niveau système mais ils ont été rapatriés dans les répertoires des applicatifs.

**Comment by patkap** [comment]
A cet instant, l'installation du module échoue:
![capture du 2018-10-09 10-25-45](https://user-images.githubusercontent.com/11497003/46656211-cdf58300-cbad-11e8-8ea8-b5b304076b61.png)
Quand on debug et log l'erreur, c'est `Missing file /home/pat/geonature/external_modules/exports/config/conf_gn_module.toml`.

**Comment by patkap** [comment]
Doooh .... il faut se placer dans le répertoire du module pour l'installer.

**Comment by camillemonchicourt** [comment]
Hum normalement on installe un module depuis le Backend de GeoNature.
Voir https://github.com/PnX-SI/gn_module_suivi_flore_territoire/blob/master/README.rst

**Comment by patkap** [comment]
done.
