### ISSUE TITLE
Plafonnement du limit ?

### ISSUE THREAD

**Issue by lpofredc** [PnX-SI/gn_module_export#198]
Bonjour, y a-t-il une raison particulière de plafonner le `limit` à 1000 résultats ?

https://github.com/PnX-SI/gn_module_export/blob/30433d41c9bbf9672e09e5b86caa705708a4837c/backend/gn_module_export/blueprint.py#L281-L282

**Comment by camillemonchicourt** [comment]
Peut-être des questions initiales de performance ou pour garantir que l'API va pas être trop chargée par un usage qui ne serait pas souhaitable et mettrait a plat le serveur.

Mais on pourrait peut-être plutôt mettre une limite à 1000 par défaut quand elle n'est pas spécifiée mais permettre d'aller à plus.
Peut-être quand même quand même garder un max à 10.000 ou plus ? Et le rendre paramétrable pour ceux qui voudraient permettre un usage avec une limite plus grande ?

**Comment by TheoLechemia** [comment]
> Mais on pourrait peut-être plutôt mettre une limite à 1000 par défaut quand elle n'est pas spécifiée mais permettre d'aller à plus.

Oui c'est un fonctionnement assez courant et logique

**Comment by camillemonchicourt** [comment]
Ajout des paramètres dans la 1.7.1 : 
- `max_page_size_api` : Max number of items for each API call (default is 1000)
- `default_page_size_api` : Default number of items returned on each API call (default is 1000)
