### ISSUE TITLE
Moissonage de Data.gouv.fr

### ISSUE THREAD

**Issue by orovellotti** [PnX-SI/gn_module_export#2]
On me transmet les informations suivantes: 

L'API data.gouv.fr  : [API](https://doc.data.gouv.fr/faq/developpeur.html#section-api)
La doc par data.gouv.fr : [FAQ](https://doc.data.gouv.fr/faq/developpeur.html#section-moissonage
) 

Aujourd’hui, les moissonneurs suivants sont disponibles :
•	CKAN (générique)
•	OpenDataSoft (générique)
•	DCAT-AP (générique)
•	maaf (spécifique Ministère de l’Agriculture, de l’Agroalimentaire et de la Forêt)

**Comment by orovellotti** [comment]
Si vous ne possédez pas de site Web et que la fréquence de mise à jour de vos données est faible, « data.gouv.fr » permet de télécharger des fichiers depuis votre ordinateur. Néanmois, si vous possédez un site Web, il est préférable de référencer vos données, évitant ainsi de devoir les mettre à jour régulièrement sur data.gouv. Par exemple, référencer la ressource http://monsite.fr/jeu_de_donnees_derniere_version.csv vous permet de déclarer une fois pour toutes une donnée avec une fréquence de mise à jour temps réel.

**Comment by camillemonchicourt** [comment]
Très bien ça !

**Comment by orovellotti** [comment]
Il faut attendre d'avoir une instance live avec des vrais données pour pouvoir l'ajouter a Data.gouv.fr ?

**Comment by camillemonchicourt** [comment]
Ça fonctionne bien. Voir http://www.ecrins-parcnational.fr/actualite/parc-national-ecrins-deconfine-donnees-biodiversite
Et https://www.data.gouv.fr/fr/datasets/observations-de-biodiversite-faune-flore-du-parc-national-des-ecrins/
