### ISSUE TITLE
fix: `get_one_export_api` doesn't return geojson when geometry field is present

### ISSUE THREAD

**Issue by edelclaux** [PnX-SI/gn_module_export#214]
Dans le module export, les données retournées par la méthode `get_one_export_api`.

Lien vers l'appel en question:
https://github.com/PnX-SI/gn_module_export/blob/200c12f68d508dc09f6c57c8abc832cea89f55d5/backend/gn_module_export/blueprint.py#L292C1-L295C32

qui gère la query retournée par la route: https://github.com/PnX-SI/gn_module_export/blob/1b8145bb50cb77bf8f658f048501ab33960c01c2/backend/gn_module_export/blueprint.py#L197C1-L302C16

https://github.com/PnX-SI/Utils-Flask-SQLAlchemy-Geo/issues/30
La solution a d'abord été discutée dans une [issue + PR](https://github.com/PnX-SI/Utils-Flask-SQLAlchemy-Geo/issues/30) dans le projet [Utils-Flask-SQLAlchemy-Geo](https://github.com/PnX-SI/Utils-Flask-SQLAlchemy-Geo).

Après plusieurs hésitations, il a été choisit de rajouter la gestion du "if geometry else" dans la méthode `get_one_export`.

**Comment by camillemonchicourt** [comment]
Fait dans la 1.7.2
