### ISSUE TITLE
interface pour associer rôles et exports

### ISSUE THREAD

**Issue by patkap** [PnX-SI/gn_module_export#25]
Pouvoir associer une entité enregistrée dans t_roles à un export enregistré dans t_exports.
Cette asso doit persister dans cor_exports_roles.
Intégrable via flask-admin dans le module admin de GéoNature.

**Comment by orovellotti** [comment]
Ok en cours

**Comment by orovellotti** [comment]
Techniquement on peut utiliser flaskAdmin ou le faire a la main 

Option d'interface
Option 1: 
Intégrer la fontionalité dans le module Exort

Option 2:
Intergrer la fontionalité dans le module Admin de geoNature


![Sans titre](https://user-images.githubusercontent.com/1989428/56415531-47250f80-628e-11e9-8853-b26e3ea87cc9.png)

**Comment by camillemonchicourt** [comment]
Si on le met dans le module d'Exports, alors il faudra gérer un CRUVED pour l'afficher ou non en fonction des droits de l'utilisateur.

Le module d'Admin dispose déjà d'un mécanisme de CRUVED par objet du module, pour afficher le sous-module ou non donc je prioriserai cette solution par facilité et par logique générique (on gère les permissions déjà dans l'Admin donc ça regroupe).

**Comment by amandine-sahl** [comment]
Par contre si export a pour valeur public=true alors tout le monde le verra dans l'interface, indépendamment du contenu de la table cor_exports_roles

**Comment by camillemonchicourt** [comment]
En cours : https://github.com/PnX-SI/gn_module_export/pull/37
