### ISSUE TITLE
licence générique

### ISSUE THREAD

**Issue by ghost** [PnX-SI/gn_module_export#26]
@camillemonchicourt : tu semblais partant pour la license ODBL
@orovellotti : recommandait un choix parmis ODBL, Etalab et CC-by[:4]

**Comment by camillemonchicourt** [comment]
Oui la licence ouverte française plus permissive est celle par défaut pour les établissements publiques.
Mais la licence ODBL est aussi homologuée pour les établissements français et pourra intéresser certains car elle oblige le partage à l'identique et n'est pas limitée à la France : https://www.data.gouv.fr/fr/licences

Idéalement il serait bien de mettre les 2 en PDF et a chaque instance de GeoNature de choisir d'utiliser l'une ou l'autre avec un paramètre ?
Cela permettrait aussi d'afficher directement sur la page des exports le nom de la licence.

Mais je me dis que certains ne voudront pas fournir leurs exports sous licence opendata donc on pourra en ajouter plus tard restrictive ?

CC-by ça sera plutôt adapté aux médias et textes au niveau de TaxHub, donc pas besoin côté GeoNature.

**Comment by orovellotti** [comment]
Moi je serais partant pour n’en mettre qu’une et l’autre dans le git quelque part.

Si on met 2 options c’est un bug cognitif qui peut être un frein à l’usage et une excuse pour ne rien faire.

**Comment by camillemonchicourt** [comment]
Oui mettons ODBL par defaut.
Et pourquoi pas le PDF de licence ouverte aussi dans le dépôt. Ceux qui voudront changer le pourront comme ça.
De toute façon, là c'est pour ceux qui téléchargent le fichier depuis l'interface de GeoNature.
Le fichier publié dynamiquement sur data.gouv.fr peut avoir une autre licence.

**Comment by orovellotti** [comment]
Ok pour moi

**Comment by patkap** [comment]
On stocke un exemplaire de chaque licence dans les assets du repo.
Une option de conf spécifie laquelle utiliser.
Le backend sert le fichier au lieux de l'embarquer dans le frontend.
