### ISSUE TITLE
génération de fichiers CSV, geojson, SHP, RDF automatique et périodique

### ISSUE THREAD

**Issue by patkap** [PnX-SI/gn_module_export#27]
... pour les exposer sur des plateformes comme data.gouv.fr.

**Comment by camillemonchicourt** [comment]
Oui basé sur le ou les exports que l'on souhaite si on veut diffuser plusieurs exports (un jeu de données type SINP, un autre a partir du protocole Suivi Flore....)

**Comment by patkap** [comment]
C'est un process dont il faut documenter la configuration et le fonctionnement.

**Comment by orovellotti** [comment]
Pas compris, vous pouvez clarifier ?

**Comment by camillemonchicourt** [comment]
Voir la doc sur le sujet - https://github.com/PnX-SI/gn_module_export#export-planifi%C3%A9

Utilisé pour la publication des observations de biodiversité du PNE, automatiquement mises à jour chaque nuit sur https://www.data.gouv.fr/fr/datasets/observations-de-biodiversite-faune-flore-du-parc-national-des-ecrins/
