### ISSUE TITLE
Unique Identifier 

### ISSUE THREAD

**Issue by orovellotti** [PnX-SI/gn_module_export#30]
Il nous faudrait une stratégie pour donner a chaque occurrence un identifiant unique et deréférençable pour être en accord avec les préceptes du web de données.

Dans l'idéal, pointer vers un atlas qui a vocation a être public serait mieux et dans tous les cas ajouter la racine URL du parc qui a instancié le geonature.

"This reﬂects the long standing convention in bioinformatics of representing identiﬁers in the form database_abbreviation: record_identiﬁer. By adopting this approach we keep identiﬁers human-readable, easy to index, and stable."

[Towards_a_biodiversity_knowledge_graph](https://www.researchgate.net/publication/300000478_Towards_a_biodiversity_knowledge_graph)

**Comment by camillemonchicourt** [comment]
Le SINP prévoyait initialement que l'ID permanent soit composé de l'URL de la plateforme, suivi d'un UUID : https://inpn.mnhn.fr/docs/standard/sinp_identifiantpermanent.pdf

Il a finalement été proposé récemment de ne garder que l'UUID et c'est donc ce qu'on a mis en place dans GeoNature : 
https://github.com/PnX-SI/GeoNature/blob/master/contrib/occtax/data/occtax.sql#L294
