### ISSUE TITLE
Export RDF utiliser une vue spécifique

### ISSUE THREAD

**Issue by amandine-sahl** [PnX-SI/gn_module_export#33]
Pour l'export RDF, il faudrait utiliser une vue spécifique qui se base sur les données de la synthèse

**Comment by orovellotti** [comment]
Reprendre la vue actuelle et la bassée sur synthèse

**Comment by orovellotti** [comment]
Créer une vue compatible SINP directement

**Comment by cdcvidal** [comment]
https://github.com/gbif/ipt/wiki/occurrenceData#templates
