### ISSUE TITLE
Interface "exporter données" -> Documentation de l'API des différent exports

### ISSUE THREAD

**Issue by orovellotti** [PnX-SI/gn_module_export#34]
Ajouter un bouton pour documenter de manière générique l'API dans la description du module.
Ce bouton revoie vers le Swagger actuel sans les spécifique SINP.

Si il existe un YML pour les exports customs afficher le bouton API, sinon ne rien afficher.

Il faut rester avec la version OpenSource de Swagger.

![export](https://user-images.githubusercontent.com/1989428/56416110-2cec3100-6290-11e9-81ae-62df8c9fb358.png)

**Comment by amandine-sahl** [comment]
A faire également : créer une documentation pour l'export SIPN qui est définie par défaut dans le module

**Comment by amandine-sahl** [comment]
Permettre à l'utilisateur de rajouter une documentation swagger spécifique à un export données.

Pour résumer 3 types de documations swagger : 
 1 - Générique pour le module 
 2 - Spécifique à l'export 1 - SINP (installé par défaut)
 3 - Spécifique à un export particulié et défini par l'utilisateur

**Comment by camillemonchicourt** [comment]
Rappel : Il est possible de choisir si les API (même celle SINP par défaut) est accessible publiquement ou non. Il s'agit d'un champs dans la BDD de mémoire. 
En effet certaines instances de GeoNature peuvent faire le choix de ne pas rendre public et ouverte leur API SINP.

**Comment by amandine-sahl** [comment]
Mécanisme mis en place et à finaliser

Pour chaque export si un fichier de configuration du swagger existe et respecte une nomenclature donnée (api_specification_{id_export}.json) alors il est utilisé sinon une documentation type est générée automatiquement.

Fichiers de configuration de swagger :
 - API générale au module : backend/templates/swagger/generic_swagger_doc.json
 - API générique pour un export : backend/templates/swagger/generic_swagger_doc.json
 - Exemple d'API spécifique à l'export numéro 2: backend/templates/swagger/api_specification_2.json.sample

**Comment by amandine-sahl** [comment]
A faire utiliser les commentaires des colonnes pour générer la description du champ
