### ISSUE TITLE
Ontologie SINP 

### ISSUE THREAD

**Issue by orovellotti** [PnX-SI/gn_module_export#35]
Il faudrait une Ontologie du Standard SINP pour pouvoir avoir tous les champs.

A voir avec le SINP/Patrinat/AFB si quelqu'un peut financer ce travail ?

**Comment by DonovanMaillard** [comment]
Sauf erreur, je crois qu'ils ont amorcé un travail du genre sur une partie de leurs référentiels.

**Comment by amandine-sahl** [comment]
cf #36
