### ISSUE TITLE
Revoir exports.sql

### ISSUE THREAD

**Issue by camillemonchicourt** [PnX-SI/gn_module_export#4]
Actuellement dans https://github.com/PnX-SI/GeoNature/blob/develop/data/core/exports.sql

- t_exports
- t_exports_logs
- bib_formats
- cor_exports_roles

Fonctionnement : 

- L'interface du module liste les exports disponibles pour l'utilisateur connecté.
- Quand l'utilisateur choisit un export, les différents formats lui sont proposés. 
- Au clic sur un format, le fichier est généré à partir de la vue et téléchargé localement.
- Chaque export est loggé dans une table.
- Une interface dans le backoffice (module Admin à créer) permet de créer des exports et d'y associer les rôles (utilisateurs ou groupes) qui y ont accès.

**Comment by gildeluermoz** [comment]
Attention, le fichier en question est un brouillon. la seule table qu'il contient n'a même de clé primaire.

**Comment by camillemonchicourt** [comment]
Actuellement ce qui a été fait dans https://github.com/vpilorge/GeoNatIntero

Population des définitions d'export
--------------------------------------

![t_exports_population](https://user-images.githubusercontent.com/4418840/41677162-d622f0f4-74c7-11e8-9645-f15b97bac8ee.png)

TODO :

- [ ] Implémentation d'un endpoint sur le backend permettant l'ajout d'extraction/export personalisé(e) et "nourrissant" le journal associé.
- [ ] Implémentation de son UI côté frontend.

Population du journal d'exports
-----------------------------------

![t_exports_logs_populate](https://user-images.githubusercontent.com/4418840/41677257-14415f56-74c8-11e8-9bf1-d2280553c395.png)

Traitement des demandes d'export de donnée
---------------------------------------------------

Une tâche Cron vient régulièrement collecter les enregistrements dont le status est positionné à "-2"(en
attente de traitement) :

`
cd ~/geonature/contrib/export && /usr/bin/python3 -m jobs
`

Selon le résultat du traitement, le statut de l'export est mis à jour : ``-1`` failure, ``0`` success.

Le nombre d'enregistrements générés, ou le traceback de l'erreur est inséré dans la colonne ``log``.

En l'état actuel, un fichier est généré et sauvegardé dans ``geonature/backend/static/exports``.

TODO:
- [ ] Supprimer les vues actuelles, les générer "à la volée".
- [ ] Implémentation du comportement dans le Cron job.
- [ ] Intégrer le modèle sqlalchemy dans le Cron job.

**Comment by camillemonchicourt** [comment]
A noter que : 

- Loguer les exports est surtout utile pour savoir qui a téléchargé quoi et quand depuis l'interface (https://github.com/PnX-SI/GeoNature/issues/193)
- Mais en effet c'est intéressant aussi de loguer les exports qui sont générés automatiquement par Cron avec le statut et le log d'erreur
- Un début de schéma ``gn_exports`` avait été amorcé : https://github.com/PnX-SI/GeoNature/blob/develop/data/core/exports.sql. 
- Les noms de tables ``t_exports`` et ``t_exports_log`` sont bien
- Pour les ID de ses 2 tables, il faudrait plutôt utiliser des Integer SERIAL
- Dans ``t_exports_log`` il faudra ajouter un champ ``id_role`` pour savoir qui a fait l'export quand celui-ci est fait à la demande depuis l'interface
- Il y a des champs à ajouter dans la table ``t_exports`` (pour définir le chemin de la vue, pour l'API d'un export, l'activer, la protéger...). Je laisse @amandine-sahl voir cette partie BDD.

AUTRES : 

- Concernant la localisation des vues : https://github.com/PnX-SI/GeoNature/issues/282
- Concernant les droits sur les exports : https://github.com/PnX-SI/GeoNature/issues/293. Pour le moment on met de côté le fait de pouvoir filtrer un export en interface et de l'adapter selon l'utilisateur connecté
- Il y a un export assez générique proposé dans 3 formats dans le module OccTax : https://github.com/PnX-SI/GeoNature/issues/363
- On a homogénéiser les noms des fichiers exportés : https://github.com/PnX-SI/GeoNature/issues/308
- Il y a aussi des développements qui peuvent servir : https://github.com/PnX-SI/GeoNature/issues/366

**Comment by camillemonchicourt** [comment]
Les développements sont désormais réalisés dans le dépot https://github.com/PnX-SI/gn_module_export/tree/primer

**Comment by amandine-sahl** [comment]
outdated
