### ISSUE TITLE
Problème avec les API

### ISSUE THREAD

**Issue by DonovanMaillard** [PnX-SI/gn_module_export#41]
Bonjour, 

je viens de faire une install du module, et je constate un problème avec l'API de l'export par défaut. Le même problème est reproduit sur le serveur de demo : 

> Fetch error
> Not Found /exports/swagger-ressources/1
>

**Comment by amandine-sahl** [comment]
Il faudrait vérifier que le module se soit installé correctement.
Est-ce que l'export est présent dans l'admin du module (API_BACKEND/admin/export/)?

**Comment by DonovanMaillard** [comment]
Bonjour amandine, 

Le module semble installé correctement, niveau conf des mails j'ai bien les csv qui s'envoient correctement, l'interface et le backoffice du module sont OK. 

L'URL api_backend n'existe pas, mais j'ai bien l'export exemple SINP et mon export toto sur l'url http://carnets.flavia-ape.fr/geonature/api/admin/export/ (c'est un serveur test avec admin/admin si besoin de voir sur pièce). 

La même erreur est présente sur demo.geonature.fr/geonature. 

Par ailleurs je ne trouve nulle part de répertoire swagger-ressources dans external_modules/exports et ses différents répertoires sur mon serveur.  N'y a-til pas des librairies qui ne se seraient pas installées? Je suis à la recherche des logs pour creuser un peu.

**Comment by amandine-sahl** [comment]
L'API d'export de données fonctionne : http://carnets.flavia-ape.fr/geonature/api/exports/api/1
Par contre, pourrais tu me donner la liste des fichiers du répertoire `external_modules/exports/backend/templates/swagger`

**Comment by DonovanMaillard** [comment]
> L'API d'export de données fonctionne : http://carnets.flavia-ape.fr/geonature/api/exports/api/1

Ok merci! Dans ce cas, c'est un soucis d'URL ciblé par le bouton "api" en interface, qui renvoie sur :
http://carnets.flavia-ape.fr/geonature/api/exports/swagger/1


Le répertoire en question comprend 3 fichiers : 

- api_specification_2.json.sample  
- main_swagger_doc.json
- generic_swagger_doc.json

**Comment by DonovanMaillard** [comment]
Ok , bien noté que le lien renvoie sur une doc, et pas sur l'API elle-même =)
