### ISSUE TITLE
Export et vues personnalisées - TypeError

### ISSUE THREAD

**Issue by skoliad** [PnX-SI/gn_module_export#44]
Bonjour

Je teste géonature (version 2.2.1) et 
je rencontre un problème dans l'utilisation du module  "gn_module_export" (version 0.1.0)

La procédure d'export  fonctionne bien tant que j'utilise la vue nommée "gn_exports.v_synthese_sinp" 
(il s'agit de la vue  créée par défaut par la procédure d'installation)

Ceci se passe bien même si j'ajoute des clauses WHERE  dans cette vue "v_synthese_sinp"

Par contre, ceci ne fonctionne plus si j'utilise un autre nom de vue dans le paramétrage des exports (table gn_exports.t_exports) 
Par exemple v_synthese_sinp2, v_synthese_sinp3, v_synthese_test...

Dans ce cas le mail reçu contient : 
"Bonjour,
Votre export n'a pas fonctionné correctement 
Detail Error when export data : TypeError("'InternalError' object is not callable",)"
 
Question
Quel est le paramètre manquant 
Que  faut il faire pour rendre mes vues "callable" ?

Cordialement
Hervé PENNARUN

Cordialement

**Comment by camillemonchicourt** [comment]
Merci pour ces tests et ce retour. 
J'ai transféré votre ticket sur le dépôt du module Export concerné par votre soucis. 

Ce module est encore en développement et la 0.1.0 est une pre-release, avec encore pas mal de choses à compléter/corriger. 
Mais le fait d'ajouter des exports en se basant sur des vues personnalisées est l'objectif de ce module et est normalement fonctionnel dans la 0.1.0.

Je laisse @cdcvidal ou @amandine-sahl, qui développent ce module, identifier d'où peut venir cette erreur.

Pouvez-vous nous indiquer le contenu de la vue que vous avez créé ?

**Comment by skoliad** [comment]
Merci pour la promptitude de votre réponse.

Pour les vues que j'ai créé, je n'ai pas fait preuve d'originalité :
J'ai repris le script sql utilisé par la procédure d'installation
et j'ai simplement ajouté des conditions pour limiter les données exportées
;

Je vous mets en pièce jointe les fichiers sql

Bonne fin de week-end.

**Comment by camillemonchicourt** [comment]
Il n'y a pas de fichier attaché.

**Comment by skoliad** [comment]
C 'est bizarre,
je les retrouve dans le mail que j'ai envoyé

Je vous les renvoie

Cordialement

Herve PENNARUN

**Comment by cdcvidal** [comment]
Pouvez-vous fournir le fichier sql de la vue ?
Merci

**Comment by TheoLechemia** [comment]
Les pièces jointes ne passent pas sur GitHub.

**Comment by skoliad** [comment]
D accord je comprends

Je les enverrai par github ce soir

Le ven. 8 nov. 2019 à 09:23, Théo Lechémia <notifications@github.com> a
écrit :

**Comment by camillemonchicourt** [comment]
Oui il faut les mettre directement dans le ticket Github en glissant le fichier dans le message.

**Comment by cdcvidal** [comment]
Je viens de faire un test en créant la vue ci-dessous (vue sql par défaut du module avec un WHERE )

> `CREATE OR REPLACE VIEW gn_exports.v_synthese_sinp2 AS
>  WITH deco AS (
>          SELECT s_1.id_synthese,
>             n1.label_default AS "ObjGeoTyp",
>             n2.label_default AS "methGrp",
>             n3.label_default AS "obsMeth",
>             n4.label_default AS "obsTech",
>             n5.label_default AS "ocEtatBio",
>             n6.label_default AS "ocStatBio",
>             n7.label_default AS "ocNat",
>             n8.label_default AS "preuveOui",
>             n9.label_default AS "difNivPrec",
>             n10.label_default AS "ocStade",
>             n11.label_default AS "ocSex",
>             n12.label_default AS "objDenbr",
>             n13.label_default AS "denbrTyp",
>             n14.label_default AS "sensiNiv",
>             n15.label_default AS "statObs",
>             n16.label_default AS "dEEFlou",
>             n17.label_default AS "statSource",
>             n18.label_default AS "typInfGeo",
>             n19.label_default AS "ocMethDet"
>            FROM gn_synthese.synthese s_1
>              LEFT JOIN ref_nomenclatures.t_nomenclatures n1 ON s_1.id_nomenclature_geo_object_nature = n1.id_nomenclature
>              LEFT JOIN ref_nomenclatures.t_nomenclatures n2 ON s_1.id_nomenclature_grp_typ = n2.id_nomenclature
>              LEFT JOIN ref_nomenclatures.t_nomenclatures n3 ON s_1.id_nomenclature_obs_meth = n3.id_nomenclature
>              LEFT JOIN ref_nomenclatures.t_nomenclatures n4 ON s_1.id_nomenclature_obs_technique = n4.id_nomenclature
>              LEFT JOIN ref_nomenclatures.t_nomenclatures n5 ON s_1.id_nomenclature_bio_status = n5.id_nomenclature
>              LEFT JOIN ref_nomenclatures.t_nomenclatures n6 ON s_1.id_nomenclature_bio_condition = n6.id_nomenclature
>              LEFT JOIN ref_nomenclatures.t_nomenclatures n7 ON s_1.id_nomenclature_naturalness = n7.id_nomenclature
>              LEFT JOIN ref_nomenclatures.t_nomenclatures n8 ON s_1.id_nomenclature_exist_proof = n8.id_nomenclature
>              LEFT JOIN ref_nomenclatures.t_nomenclatures n9 ON s_1.id_nomenclature_diffusion_level = n9.id_nomenclature
>              LEFT JOIN ref_nomenclatures.t_nomenclatures n10 ON s_1.id_nomenclature_life_stage = n10.id_nomenclature
>              LEFT JOIN ref_nomenclatures.t_nomenclatures n11 ON s_1.id_nomenclature_sex = n11.id_nomenclature
>              LEFT JOIN ref_nomenclatures.t_nomenclatures n12 ON s_1.id_nomenclature_obj_count = n12.id_nomenclature
>              LEFT JOIN ref_nomenclatures.t_nomenclatures n13 ON s_1.id_nomenclature_type_count = n13.id_nomenclature
>              LEFT JOIN ref_nomenclatures.t_nomenclatures n14 ON s_1.id_nomenclature_sensitivity = n14.id_nomenclature
>              LEFT JOIN ref_nomenclatures.t_nomenclatures n15 ON s_1.id_nomenclature_observation_status = n15.id_nomenclature
>              LEFT JOIN ref_nomenclatures.t_nomenclatures n16 ON s_1.id_nomenclature_blurring = n16.id_nomenclature
>              LEFT JOIN ref_nomenclatures.t_nomenclatures n17 ON s_1.id_nomenclature_source_status = n17.id_nomenclature
>              LEFT JOIN ref_nomenclatures.t_nomenclatures n18 ON s_1.id_nomenclature_info_geo_type = n18.id_nomenclature
>              LEFT JOIN ref_nomenclatures.t_nomenclatures n19 ON s_1.id_nomenclature_determination_method = n19.id_nomenclature
>         )
>  SELECT s.id_synthese AS "idSynthese",
>     s.unique_id_sinp AS "permId",
>     s.unique_id_sinp_grp AS "permIdGrp",
>     s.count_min AS "denbrMin",
>     s.count_max AS "denbrMax",
>     s.meta_v_taxref AS "vTAXREF",
>     s.sample_number_proof AS "sampleNumb",
>     s.digital_proof AS "preuvNum",
>     s.non_digital_proof AS "preuvNoNum",
>     s.altitude_min AS "altMin",
>     s.altitude_max AS "altMax",
>     s.the_geom_4326 AS geom,
>     s.date_min AS "dateDebut",
>     s.date_max AS "dateFin",
>     s.validator AS validateur,
>     s.observers AS observer,
>     s.id_digitiser,
>     s.determiner AS detminer,
>     s.comment_context AS "obsCtx",
>     s.comment_description AS "obsDescr",
>     s.meta_create_date,
>     s.meta_update_date,
>     d.id_dataset AS "jddId",
>     d.dataset_name AS "jddCode",
>     d.id_acquisition_framework,
>     t.cd_nom AS "cdNom",
>     t.cd_ref AS "cdRef",
>     s.nom_cite AS "nomCite",
>     public.st_x(public.st_transform(s.the_geom_point, 2154)) AS x_centroid,
>     public.st_y(public.st_transform(s.the_geom_point, 2154)) AS y_centroid,
>     COALESCE(s.meta_update_date, s.meta_create_date) AS lastact,
>     deco."ObjGeoTyp",
>     deco."methGrp",
>     deco."obsMeth",
>     deco."obsTech",
>     deco."ocEtatBio",
>     deco."ocNat",
>     deco."preuveOui",
>     deco."difNivPrec",
>     deco."ocStade",
>     deco."ocSex",
>     deco."objDenbr",
>     deco."denbrTyp",
>     deco."sensiNiv",
>     deco."statObs",
>     deco."dEEFlou",
>     deco."statSource",
>     deco."typInfGeo"
>    FROM gn_synthese.synthese s
>      JOIN taxonomie.taxref t ON t.cd_nom = s.cd_nom
>      JOIN gn_meta.t_datasets d ON d.id_dataset = s.id_dataset
>      JOIN gn_synthese.t_sources sources ON sources.id_source = s.id_source
>      JOIN deco ON deco.id_synthese = s.id_synthese
>    WHERE s.id_synthese=1;`

J'ai ensuite déclaré cet vue dans l'admin export
![Capture du 2019-11-08 11-38-03](https://user-images.githubusercontent.com/2291777/68470530-8b710080-021c-11ea-81c3-b0613e0195d1.png)

Et j'arrive bien à l'exporter en csv.

**Comment by skoliad** [comment]
Je joints mes sql de création des vues d'export



[cree_memos_export.txt](https://github.com/PnX-SI/gn_module_export/files/3826315/cree_memos_export.txt)

[cree_vue_export_1.txt](https://github.com/PnX-SI/gn_module_export/files/3826310/cree_vue_export_1.txt)
[cree_vue_export_2.txt](https://github.com/PnX-SI/gn_module_export/files/3826311/cree_vue_export_2.txt)
[cree_vue_export_3.txt](https://github.com/PnX-SI/gn_module_export/files/3826312/cree_vue_export_3.txt)

**Comment by skoliad** [comment]
J'ai sans doute un problème dans l'installation parce que je peux  modifier
les mémos seulement si j'utilise le nom de vue  vn_synthese_sipn
Si je modifie le nom de la vue
[image: image.png]

[image: image.png]
j'obtiens un message d'erreur

[image: image.png]

**Comment by camillemonchicourt** [comment]
Bonjour.
Les images ne passent par email.
Il est fortement conseillé de répondre aux issues directement sur Github, plutôt que par email car ça n'associe pas les fichiers.

**Comment by skoliad** [comment]
Je vous transmets les captures écran

J'ai sans doute un problème dans l'installation parce que je peux  modifier les mémos seulement si j'utilise le nom de vue  vn_synthese_sipn

**Avez vous déja rencontré ce problème ?**

Si je modifie le nom de la vue 

![Geonature_export_1](https://user-images.githubusercontent.com/26528193/68617026-95b62780-04c6-11ea-8962-0eb43c61cce6.png)

MESSAGE D ERREUR
![Geonature_export_3](https://user-images.githubusercontent.com/26528193/68617249-30166b00-04c7-11ea-82bf-2658b1f167dc.png)
