### ISSUE TITLE
Export sur les exports CSV et Shape

### ISSUE THREAD

**Issue by TheoLechemia** [PnX-SI/gn_module_export#45]
Sur l'export fournit pas défaut: 
j'ai l'erreur suivante sur l'export CSV:
`Detail Error when create export file : UnicodeEncodeError('ascii', '{\n "items": {\n "features": [\n {\n "type": "Feature",\n "properties": {\n "id_acquisition_framework": 1,\n "dEEFlou": "Non",\n "preuveOui": "Inconnu",\n "sensiNiv": null,\n "vTAXREF": "Taxref V11.0",\n "cdRef": 60612,\n "ocEtatBio": "Non renseigné",\n "meta_update_date": "2019-11-04 09:40:16.012250",\n "nomCite": "Lynx Boréal",\n "obsTech": "Non renseigné",\n "lastact": "2019-11-04 09:40:16.012250",\n "denbrTyp": "Compté",\n "preuvNum": "",\n "idSynthese": 1,\n "ocSex": "Femelle",\n "obsCtx": "Exemple test",\n "typInfGeo": "Géoréférencement",\n "altMin": 1500,\n "obsDescr": "Test",\n "jddId": 1,\n "altMax": 1565,\n "ocStade": "Adulte",\n "statSource": "Terrain",\n "x_centroid": 976445.725689655,\n "y_centroi ..... ordinal not in range(128)`
A noter que l'erreur ne se produit pas en dev (quand je lance le backend via la commande "geonature dev_back"). 

et celle là sur l'export shape:

`Detail Error when create export file : TypeError('lstat: illegal type for path parameter',)
`

**Comment by cdcvidal** [comment]
Sur une installation _non-dev_ de Geonature 2.2.1 avec la version Master du module Export

Je ne reproduis pas d'erreur sur l'export csv avec l'export par defaut `Synthese SINP`

mais j'ai bien l'erreur sur l'export shape

**Comment by amandine-sahl** [comment]
PB export CSV non reproduit.
SHP corrigé
