### ISSUE TITLE
Envoi mail à l'utilisateur

### ISSUE THREAD

**Issue by vpilorge** [PnX-SI/gn_module_export#5]
Bonjour, 

Nous souhaitons implémenter la fonction d'envoie de mail à l'utilisateur lorsque le traitement est terminé. Nous avons quelques questions à ce sujet:

- Y a t-il une infrastructure en place pour l'envoi de mail ?
- Peut-on confier la tâche à une API tierce ( sendgrid, mailchimp, ...) ?

Merci

**Comment by amandine-sahl** [comment]
Tu peux le faire avec [Flask-mail](https://pythonhosted.org/flask-mail/) et des paramètres dans le fichier de configuration

**Comment by vpilorge** [comment]
Ok on regarde ça, merci.

Quel serveur SMTP peut-on utiliser ? Doit-on mettre en place le service nous même ?

**Comment by camillemonchicourt** [comment]
A mon souvenir, on avait évoqué le fait que ce n'était pas forcément une solution privilégiée. 
Mettre en place un serveur SMTP au niveau du serveur apporte toujours des complexités et des problèmes de configuration. 
Il faut privilégier le fait d'afficher un message d'attente et quand c'est prêt l'interface permet de télécharger le fichier. 
On ne peut pas non plus imposer un service tiers comme Mailchimp. 

Donc pourquoi pas si c'est optionnel et configurable mais pas si c'est le fonctionnement de base.

**Comment by amandine-sahl** [comment]
Non en théorie tu peux te servir de la configuration SMTP d'un mail existant.

**Comment by patkap** [comment]
Pas de serveur smtpd à disposition.

Nous allons explorer des solutions telles que [sentry](sentry.io) pour nos instances de démo.

**Comment by camillemonchicourt** [comment]
Il n'est pas prévu d'envoi d'emails. On télécharge le fichier directement

**Comment by camillemonchicourt** [comment]
Finalement il y a un mécanisme d'envoi d'emails ?
Il est utilisé et dans quel cas ?

**Comment by amandine-sahl** [comment]
Dans la mesure où il n'est pas possible de controler le temps et le processus utilisé par un export.
Pour toutes les demandes d'export. un thread est lancé et une fois la tache finie l'utilisateur reçoit un mail.

**Comment by camillemonchicourt** [comment]
C'est obligatoire ?
On ne peut pas proposer des exports directs quitte à attendre parfois un peu longtemps ?

**Comment by amandine-sahl** [comment]
Ce serait je pense dangereux et source de problèmes de lien back/front. 
Il y a une fonctionnalité qui permet de récupérer les données en direct : l’API
