### ISSUE TITLE
[CODE_QUALITY]Factoriser et rationaliser l'usage des formats d'exports

### ISSUE THREAD

**Issue by amandine-sahl** [PnX-SI/gn_module_export#53]
La définition des formats d'export est réalisée dans le fichier de configuration. Mais il y a de multiple endroit où ils sont réécrits en dur dans le code.

Il faudrait modifier la configuration et généraliser son usage dans le code (back, front, DB)

**Comment by camillemonchicourt** [comment]
Fait dans la 1.0.1.
