### ISSUE TITLE
Erreur de droits sur le repertoire d'export 

### ISSUE THREAD

**Issue by TheoLechemia** [PnX-SI/gn_module_export#56]
Testé sur un serveur debian 10. Quand je lance à la main la commande ``geonature gn_exports_run_cron_export``, j'ai une erreur de droit sur répertoire ``backend/static/exports`` qui appartient à ``root``. Je n'ai rien lançé en `sudo` pourtant.
Je ne reproduis pas en local.
A voir si d'autres ont cette erreur

**Comment by amandine-sahl** [comment]
A priori le problème était lié à une ancienne instance du module.

En cas de problème il faut changer le propriétaire du dossier backend/static/exports avec l'utilisateur qui est priopriétaire de geonature.

En cas d'installation standard : 
`chown -r geonatureadmin:www-data backend/static/exports`
