### ISSUE TITLE
Erreur à l'installation : file-saver

### ISSUE THREAD

**Issue by DonovanMaillard** [PnX-SI/gn_module_export#58]
Bonjour pour info et à toute fin utile pour d'autres et l'intégrer à l'install si besoin, 

Lors de l'installation (debian9, sur geonature 2.3.2), l'installation s'est stoppée lors de la compilation du frontend, avec l'erreur ``Cannot find module 'file-saver'``. 

J'ai pu régler le soucis en installant le module manuellement 
``npm install file-saver --save``

Puis en relancant ``npm run build`` dans ``geonature/frontend``.

**Comment by amandine-sahl** [comment]
Le module n'utilise pas file-saver. Il n'a aucun module frontend spécifique. Je ne sais pas d'où peut venir cette erreur
