### ISSUE TITLE
Notification des erreurs directement à l'administrateur

### ISSUE THREAD

**Issue by DonovanMaillard** [PnX-SI/gn_module_export#60]
Actuellement, si un export dysfonctionne, le client reçoit un mail lui indiquant que l'export n'a pas fonctionné, et qu'il doit informer l'administrateur de la plateforme. 

On peut imaginer à termes d'avoir un mail qui prévient directement les administrateurs (tel utilisateur a souhaité activer l'export id 3 au format csv, l'export n'a pas fonctionné), et prévenir le client que son export n'a pas fonctionné mais que les administrateurs ont été informés et reviendront vers lui? 

On pourrait imaginer de définir dans la configuration du module l'id rôle de l'admin ou du groupe d'admins de la plateforme, pour que les mails d'erreurs leur soit envoyé en complément de celui envoyé au demandeur comme aujourd'hui.

**Comment by camillemonchicourt** [comment]
Si on considère que c'est l'administrateur, alors on pourrait utiliser le paramètre de GeoNature ``ERROR_MAIL_TO`` (https://github.com/PnX-SI/GeoNature/blob/master/config/default_config.toml.example#L105), plutôt que de devoir renseigner un ``id_role`` en configuration du module.

**Comment by DonovanMaillard** [comment]
oui, et ça évite de complexifier encore la configuration avec des contacts différents selon les modules :)

**Comment by camillemonchicourt** [comment]
Fait dans la 1.0.1.
