### ISSUE TITLE
Erreur lors de l'installation

### ISSUE THREAD

**Issue by samuelpriou** [PnX-SI/gn_module_export#65]
Après avoir lancé la commande geonature install_gn_module /home/geonatureadmin/gn_module_export exports. J'obtiens une erreur : 

**format_list = [(k, k) for k in current_app.config["EXPORTS"]["export_format_map"].keys()]
KeyError: 'EXPORTS**

Auriez vous une idée sur comment réparer cela ?

Voici le message entier : 

> (venv) geonatureadmin@geonatureV2:~/geonature$ geonature install_gn_module /home/geonatureadmin/gn_module_export exports
> /home/geonatureadmin/geonature/backend/venv/lib/python3.5/site-packages/psycopg2/__init__.py:144: UserWarning: The psycopg2 wheel package will be renamed from release 2.8; in order to keep installing from binary please use "pip install psycopg2-binary" instead. For details see: <http://initd.org/psycopg/docs/install.html#binary-install-from-pypi>.
>   """)
> checking file
> ...ok
> 
> 
> checking manifest
> ...ok
> 
> 
> import_requirements
> WARNING: pip is being invoked by an old script wrapper. This will fail in a future version of pip.
> Please see https://github.com/pypa/pip/issues/5599 for advice on fixing the underlying issue.
> To avoid this problem you can invoke Python with '-m pip' instead of running pip directly.
> Requirement already satisfied: rdflib==4.2.2 in ./backend/venv/lib/python3.5/site-packages (4.2.2)
> Requirement already satisfied: isodate in ./backend/venv/lib/python3.5/site-packages (from rdflib==4.2.2) (0.6.0)
> Requirement already satisfied: pyparsing in ./backend/venv/lib/python3.5/site-packages (from rdflib==4.2.2) (2.2.0)
> Requirement already satisfied: six in ./backend/venv/lib/python3.5/site-packages (from isodate->rdflib==4.2.2) (1.11.0)
> WARNING: pip is being invoked by an old script wrapper. This will fail in a future version of pip.
> Please see https://github.com/pypa/pip/issues/5599 for advice on fixing the underlying issue.
> To avoid this problem you can invoke Python with '-m pip' instead of running pip directly.
> Requirement already satisfied: python-crontab==2.4.0 in ./backend/venv/lib/python3.5/site-packages (2.4.0)
> Requirement already satisfied: python-dateutil in ./backend/venv/lib/python3.5/site-packages (from python-crontab==2.4.0) (2.6.1)
> Requirement already satisfied: six>=1.5 in ./backend/venv/lib/python3.5/site-packages (from python-dateutil->python-crontab==2.4.0) (1.11.0)
> ...ok
> 
> 
> Checking file conformity
>       install_gn_module  OK
> Traceback (most recent call last):
>   File "/home/geonatureadmin/geonature/backend/geonature/core/command/create_gn_module.py", line 77, in install_gn_module
>     .filter(TModules.module_code == module_code)
>   File "/home/geonatureadmin/geonature/backend/venv/lib/python3.5/site-packages/sqlalchemy/orm/query.py", line 3282, in one
>     raise orm_exc.NoResultFound("No row was found for one()")
> sqlalchemy.orm.exc.NoResultFound: No row was found for one()
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "/home/geonatureadmin/geonature/backend/venv/bin/geonature", line 3, in <module>
>     geonature.core.command.main()
>   File "/home/geonatureadmin/geonature/backend/venv/lib/python3.5/site-packages/click/core.py", line 722, in __call__
>     return self.main(*args, **kwargs)
>   File "/home/geonatureadmin/geonature/backend/venv/lib/python3.5/site-packages/click/core.py", line 697, in main
>     rv = self.invoke(ctx)
>   File "/home/geonatureadmin/geonature/backend/venv/lib/python3.5/site-packages/click/core.py", line 1066, in invoke
>     return _process_result(sub_ctx.command.invoke(sub_ctx))
>   File "/home/geonatureadmin/geonature/backend/venv/lib/python3.5/site-packages/click/core.py", line 895, in invoke
>     return ctx.invoke(self.callback, **ctx.params)
>   File "/home/geonatureadmin/geonature/backend/venv/lib/python3.5/site-packages/click/core.py", line 535, in invoke
>     return callback(*args, **kwargs)
>   File "/home/geonatureadmin/geonature/backend/geonature/core/command/create_gn_module.py", line 92, in install_gn_module
>     check_codefile_validity(module_path, module_code)
>   File "/home/geonatureadmin/geonature/backend/geonature/utils/gn_module_import.py", line 234, in check_codefile_validity
>     from backend.blueprint import blueprint
>   File "/home/geonatureadmin/gn_module_export/backend/blueprint.py", line 196, in <module>
>     class ExportSchedulesView(ModelView):
>   File "/home/geonatureadmin/gn_module_export/backend/blueprint.py", line 223, in ExportSchedulesView
>     format_list = [(k, k) for k in current_app.config["EXPORTS"]["export_format_map"].keys()]
> KeyError: 'EXPORTS'

_

**Comment by amandine-sahl** [comment]
Effectivement il y a soucis lors de l'installation.

**Comment by camillemonchicourt** [comment]
Corrigé dans la 1.0.3

**Comment by samuelpriou** [comment]
Hello,

Merci à @amandine-sahl, @camillemonchicourt  et Théo.
Le module s'est correctement installé.
