### ISSUE TITLE
Erreur à l'export

### ISSUE THREAD

**Issue by DonovanMaillard** [PnX-SI/gn_module_export#76]
Aucun export ne fonctionne actuellement sur mon instance, avec toujours ce retour : 

> Detail Error when create export file : TypeError('lstat: illegal type for path parameter',)

J'ai testé avec différents noms, sans accent etc. Vrai pour les 3 exports testés (avec ou sans geom).

**Comment by amandine-sahl** [comment]
fixer : https://github.com/PnX-SI/gn_module_export/commit/4a3bb94d5ae2da45122f9825c332bdee89d72323

**Comment by DonovanMaillard** [comment]
merci!

**Comment by camillemonchicourt** [comment]
Fix intégré dans la 1.0.4 sortie la semaine dernière. 
Bien préciser la version utilisée quand vous remontez un problème.
