### ISSUE TITLE
CRUVED : accès aux exports non associés

### ISSUE THREAD

**Issue by DonovanMaillard** [PnX-SI/gn_module_export#77]
Bonjour, 

Sur la version 1.0.4 j'ai différents exports associés à différents roles. Ces utilisateurs ont bien un cruved de portée 1 sur "lire" et "exporter" pour le module export, et un "lire 1" au niveau de geonature (qui du coup ne surcouche pas). 

L'utilisateur a pourtant accès à tous les exports du module. Est-ce que quelqu'un a le même soucis ?

**Comment by amandine-sahl** [comment]
Je n'ai pas réussi à reproduire le problème. Désolée

**Comment by DonovanMaillard** [comment]
Merci Amandine pour ton retour, et d'avoir regardé. Veux tu un accès à notre instance pour voir le soucis ? Je vais regarder de mon coté si je trouve une autre raison à ce soucis...

**Comment by DonovanMaillard** [comment]
Testé avec Amandine, et non reproduit.
