### ISSUE TITLE
Créer une vue "DEE" 

### ISSUE THREAD

**Issue by TheoLechemia** [PnX-SI/gn_module_export#80]
Créer une vue conforme au DEE afin de générer une API d'échange conforme au standard: http://www.naturefrance.fr/languedoc-roussillon/donnees-elementaires-dechange
La vue doit comprendre l'uuid JDD et CA pour pouvoir filtrer sur ces filtres. 

Vérifier que la vue fournie avec module n'est pas déjà au standard https://github.com/PnX-SI/gn_module_export/blob/master/data/exports.sql#L152 . Si besoin l'éditer.

**Comment by camillemonchicourt** [comment]
Oui, il y a déjà un EXPORT au format SINP assez complet.
A voir si il faut faire une autre vue dédiée.
Attention, le lien vers le format DEE est celui de LR. Bien vérifier la dernière version officielle.

**Comment by camillemonchicourt** [comment]
Fait dans la 1.2.0
