### ISSUE TITLE
Migration occtax v2

### ISSUE THREAD

**Issue by amandine-sahl** [PnX-SI/gn_module_export#82]
Modifier les vues pour prendre en compte les modifications d'occtax

**Comment by camillemonchicourt** [comment]
C'est fait dans les exports de la vue SINP fournie par défaut.
Reste à le faire dans la vue RDF : https://github.com/PnX-SI/gn_module_export/blob/develop/data/exports.sql#L351-L352
Il me semble que seul la méthode d'observation (à renommer technique d'observation) est utilisé : https://github.com/PnX-SI/gn_module_export/blob/develop/backend/rdf.py#L67
Mais pas certain. @amandine-sahl ?

**Comment by camillemonchicourt** [comment]
OK dans la 1.2.0
