### ISSUE TITLE
Problème d'installation du module (GN 2.5.2)

### ISSUE THREAD

**Issue by maximetoma** [PnX-SI/gn_module_export#85]
Bonjour,

J'ai un petit soucis avec l'installation du module sur GeoNature 2.5.2.

>   ...Test mail configuration
> Requirement already satisfied: rdflib==4.2.2 in /home/geonatureadmin/geonature/backend/venv/lib/python3.7/site-packages (from -r /home/geonatureadmin/geonature/contrib/gn_module_export/backend/requirements.txt (line 1)) (4.2.2)
> Requirement already satisfied: python-crontab==2.4.0 in /home/geonatureadmin/geonature/backend/venv/lib/python3.7/site-packages (from -r /home/geonatureadmin/geonature/contrib/gn_module_export/backend/requirements.txt (line 2)) (2.4.0)
> Requirement already satisfied: pyparsing in /home/geonatureadmin/geonature/backend/venv/lib/python3.7/site-packages (from rdflib==4.2.2->-r /home/geonatureadmin/geonature/contrib/gn_module_export/backend/requirements.txt (line 1)) (2.2.0)
> Requirement already satisfied: isodate in /home/geonatureadmin/geonature/backend/venv/lib/python3.7/site-packages (from rdflib==4.2.2->-r /home/geonatureadmin/geonature/contrib/gn_module_export/backend/requirements.txt (line 1)) (0.6.0)
> Requirement already satisfied: python-dateutil in /home/geonatureadmin/geonature/backend/venv/lib/python3.7/site-packages (from python-crontab==2.4.0->-r /home/geonatureadmin/geonature/contrib/gn_module_export/backend/requirements.txt (line 2)) (2.6.1)
> Requirement already satisfied: six in /home/geonatureadmin/geonature/backend/venv/lib/python3.7/site-packages (from isodate->rdflib==4.2.2->-r /home/geonatureadmin/geonature/contrib/gn_module_export/backend/requirements.txt (line 1)) (1.11.0)
> Traceback (most recent call last):
>   File "/home/geonatureadmin/geonature/backend/geonature/core/command/create_gn_module.py", line 77, in install_gn_module
>     .filter(TModules.module_code == module_code)
>   File "/home/geonatureadmin/geonature/backend/venv/lib/python3.7/site-packages/sqlalchemy/orm/query.py", line 3473, in one
>     raise orm_exc.NoResultFound("No row was found for one()")
> sqlalchemy.orm.exc.NoResultFound: No row was found for one()
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "/home/geonatureadmin/geonature/backend/venv/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1277, in _execute_context
>     cursor, statement, parameters, context
>   File "/home/geonatureadmin/geonature/backend/venv/lib/python3.7/site-packages/sqlalchemy/engine/default.py", line 593, in do_execute
>     cursor.execute(statement, parameters)
> psycopg2.errors.UndefinedColumn: ERREUR:  la colonne s.id_nomenclature_obs_meth n'existe pas
> LINE 233: ...LEFT JOIN ref_nomenclatures.t_nomenclatures n3 ON s.id_nomen...
>                                                                ^
> 
> 
> The above exception was the direct cause of the following exception:
> 
> Traceback (most recent call last):
>   File "/home/geonatureadmin/geonature/backend/venv/bin/geonature", line 3, in <module>
>     geonature.core.command.main()
>   File "/home/geonatureadmin/geonature/backend/venv/lib/python3.7/site-packages/click/core.py", line 722, in __call__
>     return self.main(*args, **kwargs)
>   File "/home/geonatureadmin/geonature/backend/venv/lib/python3.7/site-packages/click/core.py", line 697, in main
>     rv = self.invoke(ctx)
>   File "/home/geonatureadmin/geonature/backend/venv/lib/python3.7/site-packages/click/core.py", line 1066, in invoke
>     return _process_result(sub_ctx.command.invoke(sub_ctx))
>   File "/home/geonatureadmin/geonature/backend/venv/lib/python3.7/site-packages/click/core.py", line 895, in invoke
>     return ctx.invoke(self.callback, **ctx.params)
>   File "/home/geonatureadmin/geonature/backend/venv/lib/python3.7/site-packages/click/core.py", line 535, in invoke
>     return callback(*args, **kwargs)
>   File "/home/geonatureadmin/geonature/backend/geonature/core/command/create_gn_module.py", line 108, in install_gn_module
>     run_install_gn_module(app, module_path)
>   File "/home/geonatureadmin/geonature/backend/geonature/core/command/create_gn_module.py", line 188, in run_install_gn_module
>     gnmodule_install_app(DB, app)
>   File "/home/geonatureadmin/geonature/contrib/gn_module_export/install_gn_module.py", line 39, in gnmodule_install_app
>     open(str(MODULE_DIR / "data/exports.sql"), "r").read()
>   File "/home/geonatureadmin/geonature/backend/venv/lib/python3.7/site-packages/sqlalchemy/orm/scoping.py", line 163, in do
>     return getattr(self.registry(), name)(*args, **kwargs)
>   File "/home/geonatureadmin/geonature/backend/venv/lib/python3.7/site-packages/sqlalchemy/orm/session.py", line 1292, in execute
>     clause, params or {}
>   File "/home/geonatureadmin/geonature/backend/venv/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1011, in execute
>     return meth(self, multiparams, params)
>   File "/home/geonatureadmin/geonature/backend/venv/lib/python3.7/site-packages/sqlalchemy/sql/elements.py", line 298, in _execute_on_connection
>     return connection._execute_clauseelement(self, multiparams, params)
>   File "/home/geonatureadmin/geonature/backend/venv/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1130, in _execute_clauseelement
>     distilled_params,
>   File "/home/geonatureadmin/geonature/backend/venv/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1317, in _execute_context
>     e, statement, parameters, cursor, context
>   File "/home/geonatureadmin/geonature/backend/venv/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1511, in _handle_dbapi_exception
>     sqlalchemy_exception, with_traceback=exc_info[2], from_=e
>   File "/home/geonatureadmin/geonature/backend/venv/lib/python3.7/site-packages/sqlalchemy/util/compat.py", line 182, in raise_
>     raise exception
>   File "/home/geonatureadmin/geonature/backend/venv/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1277, in _execute_context
>     cursor, statement, parameters, context
>   File "/home/geonatureadmin/geonature/backend/venv/lib/python3.7/site-packages/sqlalchemy/engine/default.py", line 593, in do_execute
>     cursor.execute(statement, parameters)
> sqlalchemy.exc.ProgrammingError: (psycopg2.errors.UndefinedColumn) ERREUR:  la colonne s.id_nomenclature_obs_meth n'existe pas
> LINE 233: ...LEFT JOIN ref_nomenclatures.t_nomenclatures n3 ON s.id_nomen...

J'ai bien reçu le mail de confirmation mais je n'arrive pas à voir d'où vient l'erreur...
Est-ce en lien avec https://github.com/PnX-SI/gn_module_export/issues/82 ?

Merci d'avance pour votre aide,
Maxime

**Comment by camillemonchicourt** [comment]
C'est normal.
L'actuelle version du module n'est pas compatible avec la 2.5 de GeoNature, dans laquelle le modèle de données a évolué. Avec le passage à la version 2.0 du standard Occurrences de taxons.

L'erreur indique ``ERREUR: la colonne s.id_nomenclature_obs_meth n'existe pas`` et en effet ce champs a été renommé dans GeoNature 2.5 du fait de l'évolution du standard qui renomme le champs "Methode d'observation" en "Technique d'observation".

Une version compatible 2.5 du module Export est prête et en cours de finalisation dans la branche ``develop``, on la sort dans les prochains jours.

**Comment by maximetoma** [comment]
Ah oui effectivement ! Merci beaucoup, j'attendons donc la sortie de la prochaine version avec impatience :)

**Comment by camillemonchicourt** [comment]
Fait avec la 1.2.0 maintenant disponible
