### ISSUE TITLE
Liens de téléchargements générés par les utilisateurs : erreur 404 (GN en sous-domaine et https)

### ISSUE THREAD

**Issue by Splendens** [PnX-SI/gn_module_export#99]
Bonjour,

J'ai installé le module exports 1.2.4 (GN 2.6.2), tout fonctionne (backoffice du module, les fichiers sont présents dans le bon dossier, possible de les télécharger via un lien comme : `https://geonature.mondomaine.fr/api/static/exports/usr_generated/<date-heure_nom_du_fichier.format>`) mais impossible de paramétrer correctement les [url de téléchargement pour les utilisateurs](https://github.com/PnX-SI/gn_module_export/blob/master/README.md#url-des-fichiers).

Les questions sur Apache sont un peu limites vu que pas liées directement à GeoNature... mais je tente quand même de lancer une bouteille à la mer ! Car sans lien de téléchargement fonctionnels pour les utilisateurs, ce module est inutilisable.

J'ai une URL d'accès en sous-domaine et HTTPS, du style` https://geonature.mondomaine.fr/`

Dans le fichier de config du module d'exports, `export_web_url ` est renseigné en `https://geonature.mondomaine.fr/exportfiles`

Et pour Apache, toujours en suivant la doc du module, j'ai ajouté les lignes :

```
Alias "/exportfiles" "/home/geonatureadmin/geonature/backend/static/exports/usr_generated"
<Directory "/home/geonatureadmin/geonature/backend/static/exports/usr_generated">
   AllowOverride None
   Require all granted
</Directory>
```

Les liens générés sont bien comme attendus (`https://geonature.mondomaine.fr/exportfiles/<date-heure_nom_du_fichier.format>`) mais ils me retournent une erreur 404. Et si je ne paramètre pas `export_web_url ` dans le fichier de conf, le mail envoyé contient une url inutilisable pour les utilisateurs :
`Votre export <le_nom_de_lexport> est accessible via le lien suivant : [/api/static/exports/usr_generated/<date-heure_nom_du_fichier.format>]Téléchargement.`

**Est-ce que quelqu'un aurait un exemple de fichier de conf apache de geonature  en sous-domaine et ssl avec un alias qui fonctionne pour les exports ?**

**Comment by camillemonchicourt** [comment]
Nos exports à la demande sont sur cet URL : https://monurl.fr/exportfiles/2021-04-12_09-46-29_monfichier.csv

La conf du module : 

```
## URL des exports générés par les utilisateurs
export_web_url='https://monurl.fr/exportfiles'
```

La conf Apache : 

```
<IfModule mod_ssl.c>
    <VirtualHost *:443>
            ServerName monurl.fr
            DocumentRoot /home/myuser/geonature/frontend/dist
	    #Alias / /home/myuser/geonature/frontend/dist
            <Directory /home/myuser/geonature/frontend/dist>
                    Require all granted
            </Directory>
                        
            # Ajout alias export donnees
            Alias "/dataexport" "/home/myuser/geonature/backend/static/exports/schedules"
            <Directory "/home/myuser/geonature/backend/static/exports/schedules">
                AllowOverride None
                Require all granted
            </Directory>
            Alias "/exportfiles" "/home/myuser/geonature/backend/static/exports/usr_generated"
            <Directory "/home/myuser/geonature/backend/static/exports/usr_generated">
                AllowOverride None
                Require all granted
            </Directory>
            # Fin alias Exports

            <Location /api>
                    ProxyPass http://127.0.0.1:8000 timeout=300
                    ProxyPassReverse  http://127.0.0.1:8000
            </Location>
    
Include /etc/letsencrypt/options-ssl-apache.conf
SSLCertificateFile /etc/letsencrypt/live/xxxxxx-0001/fullchain.pem
SSLCertificateKeyFile /etc/letsencrypt/live/xxxxxx-0001/privkey.pem
</VirtualHost>
</IfModule>
```

Il y a une histoire d'alias qui doivent être dans le bon ordre, je me souviens plus bien, il faut regarder la documentation Apache sur les alias.

Il y a peut-être quelque chose à préciser/clarifier dans la doc du module car on avait un peu galéré à expliquer cette partie.

**Comment by Splendens** [comment]
Merci pour ta réponse !

Ma config Apache ressemble plus à celle de la doc de GeoNature : [http://docs.geonature.fr/conf-apache.html#mettre-a-jour-les-configurations-apache-de-chaque-application](http://docs.geonature.fr/conf-apache.html#mettre-a-jour-les-configurations-apache-de-chaque-application)

J'ai essayé avec l'exemple de conf que tu as partagé et tout fonctionne bien... sauf cet alias ! Tant pis, je contourne le problème en renseignant le chemin complet d'accès au fichier pour le paramètre `export_web_url`.

**Comment by camillemonchicourt** [comment]
Je ne suis pas certain de cette configuration dans cette documentation.
On ne devrait pas mettre une doc HTTPS comme ça dans la doc GeoNature, car c'est lié à Apache et pas GeoNature, et ce n'est plus forcément à jour, comme indiqué récemment dans un autre ticket.
Pour nous, tu as notre conf Apache SSL qui fonctionne bien ci-dessus.

Moi aussi dans le paramètre ``export_web_url``, j'ai l'URL complète, je crois que c'est normal, ou je ne sais plus trop. :-)
Moi et Apache... ça fait 2...

**Comment by Splendens** [comment]
Ok, merci pour les précisions sur Apache, je vais _(essayer de)_ changer mes conf du coup !

> Moi et Apache... ça fait 2...

Haha, oui pareil... comme tu as pu le remarquer !


Pour l'URL complète dans le paramètre `export_web_url`, j'ai mis le chemin d'accès complet au dossier des exports plutôt que le raccourci de l'alias :  ` export_web_url='https://geonature.domain.fr/api/static/exports/usr_generated'`.  C'est pas beau mais ça a le mérite de fonctionner.

**Comment by camillemonchicourt** [comment]
Justement l'objectif de tout ça est de ne pas passer par l'API qui passe par gunicorn qui permet pas les téléchargements de gros fichier mais bien de passer par Apache qui bloque pas les gros téléchargements.

**Comment by Idaline** [comment]
Ca marche bien avec la conf de Camille. 
Pour les prochains, je donne plus de détails, la conf est à ajouter à etc/apaches/site-available/geonature.conf (à modifier en sudo).
Penser à redémarrer apache : sudo /etc/init.d/apache2 restart

**Comment by camillemonchicourt** [comment]
Ce n'est plus nécessaire d'adapter la conf Apache de GeoNature depuis la version 1.4.0 du module, où tout est géré de base dans GeoNature désormais (depuis sa version 2.12.0).
